### ISSUE TITLE
4.22 Version please?

### ISSUE THREAD

**Issue by CRIMSONCAKE** [ue4plugins/LoadingScreen#49]
Hi, does the 4.21 version work in 4.22? or should we wait?

**Comment by andyrst** [comment]
Not working on 4.22. Just black screen.

**Comment by alanedwardes** [comment]
This is fixed in 4.22.1: https://github.com/ue4plugins/LoadingScreen/issues/50#issuecomment-486747468

**Comment by kramerkra** [comment]
Still not working for me on 4.22.1. Cant compile or load plugin at all

**Comment by lucastucious** [comment]
This issues is already listed here : https://github.com/ue4plugins/LoadingScreen/issues/48

**Comment by lucastucious** [comment]
> 
> 
> Still not working for me on 4.22.1. Cant compile or load plugin at all

Try this . https://github.com/ue4plugins/LoadingScreen/issues/48#issuecomment-498276020
